import { enrichLocation } from "./catalog";
import type { FishingLocation, SourceRecord } from "./types";

const verified = "2026-08-30";
const fishOnlineUrl =
  "https://www.lioapplications.lrc.gov.on.ca/fishonline/Index.html?viewer=FishONLine.FishONLine&locale=en-CA";

const fishOnlineSource: SourceRecord = {
  name: "Ontario Fish ON-Line",
  url: fishOnlineUrl,
  lastVerified: verified,
  kind: "official",
};

const regulationsSource: SourceRecord = {
  name: "Ontario Fishing Regulations Summary",
  url: "https://www.ontario.ca/document/ontario-fishing-regulations-summary",
  lastVerified: verified,
  kind: "official",
};

const destinationOntarioSource: SourceRecord = {
  name: "Destination Ontario fishing guide",
  url: "https://www.destinationontario.com/en-ca/things-to-do/outdoor-adventures/fishing",
  lastVerified: verified,
  kind: "provincial-tourism",
};

const directions = (query: string) =>
  `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;

const sources = (name: string, tourism = false): SourceRecord[] => [
  fishOnlineSource,
  regulationsSource,
  ...(tourism ? [destinationOntarioSource] : []),
  {
    name: `${name} access notes`,
    url: directions(name),
    lastVerified: verified,
    kind: "curated",
  },
];

const rawLocations: FishingLocation[] = [
  {
    id: "ashbridges-bay", slug: "ashbridges-bay", name: "Ashbridges Bay Park",
    region: "Southern Ontario", municipality: "Toronto", bodyType: "bay-harbour", fmz: "fmz-20",
    coordinates: { latitude: 43.6584, longitude: -79.3088 },
    accessModes: ["shore", "pier", "kayak", "boat"], shoreSuitability: "excellent",
    familyFriendly: true, popularity: "featured", parking: "Large public lots near the marina and park; busy on summer weekends.",
    fees: "Park access is free; marina, launch, and event parking fees may apply.",
    facilities: ["washrooms", "picnic areas", "marina", "boat launch", "transit nearby"],
    directionsUrl: directions("Ashbridges Bay Park Toronto Ontario"), fishOnlineUrl,
    expectedSpecies: ["Chinook salmon", "Northern pike", "Smallmouth bass", "Largemouth bass", "Rock bass", "Yellow perch", "Crappie", "Bluegill", "Pumpkinseed", "Brown bullhead", "Carp"],
    beginnerTargets: ["pike", "bass", "perch/panfish", "carp"],
    tackleNotes: "Pike: spoon or spinnerbait with a leader. Bass: weedless plastics or crankbaits. Panfish: small jig or worm. Carp: corn or dough where permitted.",
    accessNotes: "Sheltered bay and Lake Ontario shore with good beginner shore access.",
    baitRules: "FMZ 20 Great Lakes bait movement rules apply. Check posted park signs.",
    cautions: ["Verify the exact waterbody on Fish ON-Line before keeping fish.", "Breakwalls can be slippery in waves."],
    sources: sources("Ashbridges Bay Park"),
  },
  {
    id: "tommy-thompson", slug: "tommy-thompson", name: "Tommy Thompson Park",
    region: "Southern Ontario", municipality: "Toronto", bodyType: "lake-shore", fmz: "fmz-20",
    coordinates: { latitude: 43.6326, longitude: -79.3316 },
    accessModes: ["shore", "pier", "kayak"], shoreSuitability: "good", familyFriendly: true,
    popularity: "popular", parking: "Limited parking near the park entrance; expect a long walk or cycle.",
    fees: "Free park access.", facilities: ["portable washrooms seasonally", "trails", "bike racks"],
    directionsUrl: directions("Tommy Thompson Park Toronto Ontario"), fishOnlineUrl,
    expectedSpecies: ["Northern pike", "Largemouth bass", "Rock bass", "Yellow perch", "Crappie", "Bluegill", "Pumpkinseed", "Brown bullhead", "Carp"],
    beginnerTargets: ["pike", "largemouth bass", "perch/panfish"],
    tackleNotes: "Pike spoons and jerkbaits, weedless bass plastics, and small panfish hooks or jigs.",
    accessNotes: "Lake Ontario peninsula with rocky shore and sheltered bays; substantial walking is required.",
    baitRules: "FMZ 20 bait rules apply; posted signs govern where fishing is allowed.",
    cautions: ["Check park access hours and seasonal closures.", "Exposed outer shoreline can become unsafe in wind and waves."],
    sources: sources("Tommy Thompson Park"),
  },
  {
    id: "toronto-islands", slug: "toronto-islands", name: "Toronto Islands",
    region: "Southern Ontario", municipality: "Toronto", bodyType: "bay-harbour", fmz: "fmz-20",
    coordinates: { latitude: 43.6205, longitude: -79.3783 },
    accessModes: ["shore", "pier", "kayak", "boat"], shoreSuitability: "excellent", familyFriendly: true,
    popularity: "featured", parking: "Use paid downtown parking before taking the ferry; no visitor cars on the islands.",
    fees: "Ferry fare required; rentals and marina services cost extra.",
    facilities: ["washrooms", "food concessions seasonally", "picnic areas", "ferry", "marina"],
    directionsUrl: directions("Toronto Islands Ontario"), fishOnlineUrl,
    expectedSpecies: ["Northern pike", "Smallmouth bass", "Largemouth bass", "Walleye", "Rock bass", "Yellow perch", "Crappie", "Bluegill", "Pumpkinseed", "Brown bullhead", "Carp"],
    beginnerTargets: ["pike", "bass", "perch", "walleye"],
    tackleNotes: "Pike spoons and spinnerbaits, bass tubes and stickbaits, and walleye jigs or dusk crankbaits.",
    accessNotes: "Productive lagoons, canals, and Lake Ontario shore; ferry access is required.",
    baitRules: "FMZ 20 bait rules apply.",
    cautions: ["Plan around the ferry schedule.", "Keep clear of ferry lanes and posted no-fishing areas."],
    sources: sources("Toronto Islands"),
  },
  {
    id: "humber-bay", slug: "humber-bay", name: "Humber Bay Park / Humber River mouth",
    region: "Southern Ontario", municipality: "Toronto", bodyType: "river-mouth", fmz: "fmz-20",
    fmzNote: "FMZ 20 near the lake and bay; FMZ 16 in the river. This is boundary-sensitive.",
    coordinates: { latitude: 43.6292, longitude: -79.4768 },
    accessModes: ["shore", "pier", "kayak", "boat"], shoreSuitability: "excellent", familyFriendly: true,
    popularity: "featured", parking: "Public lots in Humber Bay Park; spaces fill quickly on warm weekends.",
    fees: "Free park access; launch or marina services may charge.",
    facilities: ["washrooms", "trails", "picnic areas", "marina nearby"],
    directionsUrl: directions("Humber Bay Park Toronto Ontario"), fishOnlineUrl,
    expectedSpecies: ["Chinook salmon", "Coho salmon", "Rainbow trout", "Brown trout", "Northern pike", "Bass", "Panfish", "Brown bullhead", "Carp"],
    beginnerTargets: ["pike", "bass", "carp", "seasonal salmon/trout"],
    tackleNotes: "Use spoons or roe imitations for salmonids where legal and standard pike, bass, or carp setups in the bay.",
    accessNotes: "Lake Ontario bay plus a river mouth; confirm which side of the FMZ boundary you are fishing.",
    baitRules: "FMZ 16 tributary bait rules apply in the river and FMZ 20 rules on the bay.",
    cautions: ["Verify the FMZ boundary on Fish ON-Line.", "Check Humber River exceptions, sanctuary dates, and water conditions."],
    sources: sources("Humber Bay Park"),
  },
  {
    id: "etienne-brule", slug: "etienne-brule", name: "Etienne Brulé Park / lower Humber River",
    region: "Southern Ontario", municipality: "Toronto", bodyType: "river-tributary", fmz: "fmz-16",
    coordinates: { latitude: 43.6599, longitude: -79.5067 },
    accessModes: ["shore", "fly"], shoreSuitability: "good", familyFriendly: false, popularity: "popular",
    parking: "Small public lots and street parking near park entrances; obey seasonal restrictions.",
    fees: "Free park access.", facilities: ["trails", "picnic tables", "transit nearby"],
    directionsUrl: directions("Etienne Brule Park Toronto Ontario"), fishOnlineUrl,
    expectedSpecies: ["Chinook salmon", "Coho salmon", "Rainbow trout", "Brown trout", "Atlantic salmon"],
    beginnerTargets: ["seasonal salmon/trout"],
    tackleNotes: "Spoons, spinners, crankbaits, beads, or flies only where current rules permit.",
    accessNotes: "Lower Humber tributary fishing from established park access.",
    baitRules: "FMZ 16 Southern Bait Management Zone rules restrict live and dead baitfish movement.",
    cautions: ["Check section-specific exceptions, sanctuary dates, and hook or bait rules.", "Avoid wading during high or fast water."],
    sources: sources("Etienne Brule Park"),
  },
  {
    id: "rouge-marsh", slug: "rouge-marsh", name: "Rouge River Marsh",
    region: "Southern Ontario", municipality: "Toronto", bodyType: "marsh", fmz: "fmz-16",
    fmzNote: "The FMZ 16 and FMZ 20 boundary is nearby; verify the exact fishing position.",
    coordinates: { latitude: 43.797, longitude: -79.1192 },
    accessModes: ["shore", "kayak"], shoreSuitability: "limited", familyFriendly: false, popularity: "popular",
    parking: "Rouge Beach parking is limited and may be affected by construction or closures.",
    fees: "No general park admission; parking restrictions may apply.",
    facilities: ["trails", "seasonal washrooms nearby", "transit nearby"],
    directionsUrl: directions("Rouge Beach Toronto Ontario"), fishOnlineUrl,
    expectedSpecies: ["Chinook salmon", "Coho salmon", "Rainbow trout", "Brown trout", "Northern pike", "Bass", "Panfish", "Brown bullhead", "Carp"],
    beginnerTargets: ["pike", "bass", "panfish", "seasonal trout/salmon"],
    tackleNotes: "Compact pike and bass lures, small panfish rigs, and seasonal salmonid spoons or spinners.",
    accessNotes: "A river marsh connected to Lake Ontario; confirm Parks Canada access before travel.",
    baitRules: "Verify bait rules for the exact waterbody section.",
    cautions: ["Check current construction and closure notices.", "Soft marsh edges, current, and lake waves can be hazardous."],
    sources: sources("Rouge River Marsh"),
  },
  {
    id: "colonel-samuel-smith", slug: "colonel-samuel-smith", name: "Colonel Samuel Smith Park",
    region: "Southern Ontario", municipality: "Toronto", bodyType: "lake-shore", fmz: "fmz-20",
    coordinates: { latitude: 43.5932, longitude: -79.5104 },
    accessModes: ["shore", "pier", "kayak", "boat"], shoreSuitability: "good", familyFriendly: true,
    popularity: "popular", parking: "Public park and college lots; check posted limits and event restrictions.",
    fees: "Free park access.", facilities: ["washrooms seasonally", "trails", "picnic areas", "marina"],
    directionsUrl: directions("Colonel Samuel Smith Park Toronto Ontario"), fishOnlineUrl,
    expectedSpecies: ["Chinook salmon", "Coho salmon", "Rainbow trout", "Brown trout", "Northern pike", "Smallmouth bass", "Largemouth bass", "Yellow perch", "Panfish", "Brown bullhead", "Carp"],
    beginnerTargets: ["pike", "bass", "perch/panfish"],
    tackleNotes: "Spoons or spinnerbaits for pike, tubes or plastics for bass, and small hooks or jigs for panfish.",
    accessNotes: "Lake Ontario waterfront and marina shoreline with paved trails.",
    baitRules: "FMZ 20 bait rules apply.",
    cautions: ["Watch wind and wave conditions on breakwalls.", "Stay out of marina operations and posted restricted areas."],
    sources: sources("Colonel Samuel Smith Park"),
  },
  {
    id: "heart-lake", slug: "heart-lake", name: "Heart Lake Conservation Area",
    region: "Southern Ontario", municipality: "Brampton", bodyType: "conservation-lake", fmz: "fmz-16",
    fmzNote: "Verify the exact waterbody and current stocked-fish rules on Fish ON-Line.",
    coordinates: { latitude: 43.7432, longitude: -79.7894 },
    accessModes: ["shore", "pier"], shoreSuitability: "excellent", familyFriendly: true, popularity: "featured",
    parking: "On-site conservation-area parking.",
    fees: "Conservation-area admission and fishing fees may apply.",
    facilities: ["washrooms", "picnic areas", "accessible fishing dock", "rentals seasonally"],
    directionsUrl: directions("Heart Lake Conservation Area Brampton Ontario"), fishOnlineUrl,
    expectedSpecies: ["Stocked rainbow trout", "Largemouth bass", "Panfish", "Carp"],
    beginnerTargets: ["stocked trout", "bass", "panfish"],
    tackleNotes: "Small spoons, spinners, trout jigs, or a worm under a float where posted rules allow.",
    accessNotes: "Managed conservation-area lake with straightforward family access.",
    baitRules: "TRCA property rules prohibit live bait except worms; artificial lures are permitted subject to posted rules.",
    cautions: ["Confirm admission, fishing fees, hours, and current property rules before visiting."],
    sources: sources("Heart Lake Conservation Area"),
  },
  {
    id: "bluffers-park", slug: "bluffers-park", name: "Bluffer's Park / Scarborough Bluffs",
    region: "Southern Ontario", municipality: "Toronto", bodyType: "bay-harbour", fmz: "fmz-20",
    coordinates: { latitude: 43.7064, longitude: -79.2311 },
    accessModes: ["shore", "pier", "kayak", "boat"], shoreSuitability: "good", familyFriendly: true,
    popularity: "featured", parking: "Large public lots, often full on summer weekends; seasonal controls may apply.",
    fees: "Park access is free; launch and marina services may charge.",
    facilities: ["washrooms seasonally", "picnic areas", "marina", "boat launch"],
    directionsUrl: directions("Bluffers Park Toronto Ontario"), fishOnlineUrl,
    expectedSpecies: ["Chinook salmon", "Brown trout", "Carp", "Northern pike", "Bass", "Brown bullhead", "Yellow perch", "Panfish"],
    beginnerTargets: ["pike", "bass", "perch", "seasonal trout/salmon"],
    tackleNotes: "Spoons, spinners, or jerkbaits for open water; bass plastics and small panfish jigs in sheltered areas.",
    accessNotes: "Lake Ontario harbour, breakwalls, and shoreline.",
    baitRules: "FMZ 20 bait rules apply.",
    cautions: ["Breakwalls are slippery and exposed to waves.", "Do not approach unstable bluff faces."],
    sources: sources("Bluffers Park"),
  },
  {
    id: "biidaasige-park", slug: "biidaasige-park", name: "Biidaasige Park / renaturalized Don River",
    region: "Southern Ontario", municipality: "Toronto", bodyType: "river-tributary", fmz: "fmz-16",
    coordinates: { latitude: 43.6502, longitude: -79.341 },
    accessModes: ["shore"], shoreSuitability: "good", familyFriendly: true, popularity: "popular",
    parking: "Limited nearby public parking; cycling and transit are practical alternatives.",
    fees: "Free park access.", facilities: ["trails", "lookouts", "transit nearby"],
    directionsUrl: directions("Biidaasige Park Toronto Ontario"), fishOnlineUrl,
    expectedSpecies: ["Northern pike", "Largemouth bass", "Walleye", "Panfish", "Seasonal salmonids"],
    beginnerTargets: ["pike", "bass", "walleye", "panfish"],
    tackleNotes: "Compact spinnerbaits, 1/8–1/4 oz jigs, soft plastics, and small spoons.",
    accessNotes: "Use only signed fishing locations in the Don River and wetland habitat.",
    baitRules: "FMZ 16 Southern Bait Management Zone rules apply.",
    cautions: ["Follow posted signs and Don River section-specific rules.", "New habitat and access conditions may change."],
    sources: sources("Biidaasige Park"),
  },
  {
    id: "glen-haffy", slug: "glen-haffy", name: "Glen Haffy Conservation Park",
    region: "Southern Ontario", municipality: "Caledon", bodyType: "conservation-lake", fmz: "fmz-16",
    fmzNote: "Verify current pond rules and stocking information.",
    coordinates: { latitude: 43.9475, longitude: -79.914 },
    accessModes: ["shore", "pier"], shoreSuitability: "excellent", familyFriendly: true, popularity: "popular",
    parking: "On-site conservation-park parking.",
    fees: "Admission and angling fees may apply.",
    facilities: ["washrooms", "picnic areas", "fishing docks", "trails"],
    directionsUrl: directions("Glen Haffy Conservation Park Caledon Ontario"), fishOnlineUrl,
    expectedSpecies: ["Stocked rainbow trout"],
    beginnerTargets: ["stocked trout"],
    tackleNotes: "Small spoons, inline spinners, micro-jigs, or a worm under a float.",
    accessNotes: "Managed TRCA stocked-trout ponds with easy shore and dock access.",
    baitRules: "TRCA property rules prohibit live bait except worms; artificial lures are permitted subject to posted rules.",
    cautions: ["Check admission, angling fees, hours, and stocking schedule before travel."],
    sources: sources("Glen Haffy Conservation Park"),
  },
  {
    id: "lake-simcoe", slug: "lake-simcoe", name: "Lake Simcoe",
    region: "Central Ontario", municipality: "Barrie / Orillia / Georgina", bodyType: "large-lake", fmz: "fmz-16",
    coordinates: { latitude: 44.435, longitude: -79.37 },
    accessModes: ["pier", "boat", "kayak", "ice"], shoreSuitability: "limited", familyFriendly: true,
    popularity: "featured", parking: "Municipal waterfront parking varies by access point; many launches charge.",
    fees: "Launch, parking, hut, or marina fees may apply.",
    facilities: ["public launches", "marinas", "ice-hut operators", "waterfront parks"],
    directionsUrl: directions("Lake Simcoe Ontario"), fishOnlineUrl,
    expectedSpecies: ["Lake trout", "Whitefish", "Yellow perch", "Smallmouth bass", "Largemouth bass", "Northern pike"],
    beginnerTargets: ["yellow perch", "bass"],
    tackleNotes: "Perch use small jigs; bass use tubes or drop-shots. Deep-water trout and whitefish require specialized boat or ice tactics.",
    accessNotes: "Choose a named municipal pier, launch, or outfitter rather than treating the whole lake as one access point.",
    baitRules: "FMZ 16 rules and Lake Simcoe-specific exceptions apply.",
    cautions: ["A large, fast-changing lake; check marine forecasts.", "Never assume ice is safe—use local operators and current reports."],
    sources: sources("Lake Simcoe", true),
  },
  {
    id: "lake-couchiching", slug: "lake-couchiching", name: "Lake Couchiching",
    region: "Central Ontario", municipality: "Orillia", bodyType: "large-lake", fmz: "fmz-16",
    coordinates: { latitude: 44.635, longitude: -79.37 },
    accessModes: ["shore", "pier", "boat", "kayak", "ice"], shoreSuitability: "good", familyFriendly: true,
    popularity: "popular", parking: "Municipal waterfront lots and launch parking in Orillia.",
    fees: "Some parking and boat-launch fees apply.", facilities: ["waterfront parks", "washrooms", "marinas", "boat launches"],
    directionsUrl: directions("Lake Couchiching Orillia Ontario"), fishOnlineUrl,
    expectedSpecies: ["Smallmouth bass", "Largemouth bass", "Northern pike", "Yellow perch", "Walleye"],
    beginnerTargets: ["bass", "pike", "yellow perch"],
    tackleNotes: "Try small jigs from shore, or tubes, spinnerbaits, and jerkbaits around vegetation and rock.",
    accessNotes: "Orillia waterfront provides practical access; boaters can reach broader structure.",
    baitRules: "FMZ 16 bait and season rules apply.",
    cautions: ["Open-water wind can build quickly.", "Verify ice conditions locally before winter access."],
    sources: sources("Lake Couchiching"),
  },
  {
    id: "muskoka-lakes", slug: "muskoka-lakes", name: "Muskoka Lakes",
    region: "Central Ontario", municipality: "Bracebridge / Gravenhurst / Muskoka Lakes", bodyType: "large-lake", fmz: "fmz-15",
    coordinates: { latitude: 45.02, longitude: -79.57 },
    accessModes: ["boat", "kayak", "ice"], shoreSuitability: "boat-oriented", familyFriendly: false,
    popularity: "featured", parking: "Use designated municipal launches; parking capacity and trailer rules vary.",
    fees: "Launch, marina, rental, and parking fees vary.",
    facilities: ["boat launches", "marinas", "lodges", "rentals"],
    directionsUrl: directions("Lake Muskoka Ontario"), fishOnlineUrl,
    expectedSpecies: ["Lake trout", "Smallmouth bass", "Northern pike", "Walleye", "Yellow perch"],
    beginnerTargets: ["smallmouth bass", "yellow perch"],
    tackleNotes: "Boat-based trolling or jigging for trout and walleye; tubes, jerkbaits, and topwater lures for bass.",
    accessNotes: "Lake Muskoka, Lake Rosseau, and Lake Joseph are distinct waters; select an exact launch and verify its zone.",
    baitRules: "FMZ 15 rules apply in much of the area; verify each lake and exceptions.",
    cautions: ["Heavy boat traffic, exposed crossings, and complex rock hazards demand marine charts and safety gear.", "Do not use this regional pin as a launch location."],
    sources: sources("Muskoka Lakes", true),
  },
  {
    id: "georgian-bay", slug: "georgian-bay", name: "Georgian Bay",
    region: "Central Ontario", municipality: "Parry Sound / Midland / Collingwood", bodyType: "large-lake", fmz: "fmz-14",
    fmzNote: "Georgian Bay spans regulation boundaries and exceptions; verify the exact bay or tributary.",
    coordinates: { latitude: 45.2, longitude: -80.1 },
    accessModes: ["boat", "kayak", "ice"], shoreSuitability: "boat-oriented", familyFriendly: false,
    popularity: "featured", parking: "Designated harbour and launch parking varies by community.",
    fees: "Launch, marina, parking, and outfitter fees are common.",
    facilities: ["marinas", "boat launches", "lodges", "marine services"],
    directionsUrl: directions("Georgian Bay Ontario"), fishOnlineUrl,
    expectedSpecies: ["Lake trout", "Walleye", "Smallmouth bass", "Northern pike", "Muskellunge", "Salmon"],
    beginnerTargets: ["smallmouth bass", "northern pike"],
    tackleNotes: "A boat-oriented fishery using trolling, jigging, casting, and electronics appropriate to the target and basin.",
    accessNotes: "Select a protected local harbour and exact launch; this regional anchor is not a single access point.",
    baitRules: "Verify FMZ, bait management zone, and local exceptions for the exact location.",
    cautions: ["Cold water, fog, sudden wind, shoals, and long exposed runs make this advanced big water.", "Sea-kayak training and full safety equipment are essential."],
    sources: sources("Georgian Bay", true),
  },
  {
    id: "kawartha-lakes", slug: "kawartha-lakes", name: "Kawartha Lakes",
    region: "Central Ontario", municipality: "Kawartha Lakes / Peterborough", bodyType: "large-lake", fmz: "fmz-17",
    coordinates: { latitude: 44.45, longitude: -78.75 },
    accessModes: ["shore", "pier", "boat", "kayak", "ice"], shoreSuitability: "good", familyFriendly: true,
    popularity: "featured", parking: "Municipal parks and launches serve individual lakes; trailer parking varies.",
    fees: "Some launches, locks, parking areas, and rentals charge fees.",
    facilities: ["boat launches", "marinas", "waterfront parks", "lodges"],
    directionsUrl: directions("Kawartha Lakes Ontario"), fishOnlineUrl,
    expectedSpecies: ["Muskellunge", "Walleye", "Largemouth bass", "Smallmouth bass", "Crappie", "Yellow perch"],
    beginnerTargets: ["bass", "crappie", "yellow perch"],
    tackleNotes: "Small jigs for panfish, weedless plastics for bass, and larger bucktails or jerkbaits for experienced muskie anglers.",
    accessNotes: "A chain of distinct lakes; choose an exact lake and public access before departure.",
    baitRules: "FMZ 17 rules and waterbody exceptions apply.",
    cautions: ["Locks, navigation channels, weeds, and boat traffic require care.", "Muskie handling requires large nets, cutters, and experience."],
    sources: sources("Kawartha Lakes", true),
  },
  {
    id: "rice-lake", slug: "rice-lake", name: "Rice Lake",
    region: "Central Ontario", municipality: "Otonabee-South Monaghan / Hamilton Township", bodyType: "large-lake", fmz: "fmz-17",
    coordinates: { latitude: 44.17, longitude: -78.22 },
    accessModes: ["pier", "boat", "kayak", "ice"], shoreSuitability: "limited", familyFriendly: true,
    popularity: "popular", parking: "Public and commercial launch parking is available around the lake.",
    fees: "Many launches, resorts, and rentals charge fees.", facilities: ["boat launches", "resorts", "marinas", "rentals"],
    directionsUrl: directions("Rice Lake Ontario"), fishOnlineUrl,
    expectedSpecies: ["Walleye", "Largemouth bass", "Smallmouth bass", "Muskellunge", "Crappie", "Bluegill"],
    beginnerTargets: ["crappie", "bluegill", "bass"],
    tackleNotes: "Use small float rigs and jigs for panfish, weedless plastics for bass, and jigs or crankbaits for walleye.",
    accessNotes: "Most productive access is through a public launch, resort, or marina.",
    baitRules: "FMZ 17 rules and Rice Lake exceptions apply.",
    cautions: ["Shallow water can become rough quickly.", "Confirm winter ice conditions with a local operator."],
    sources: sources("Rice Lake"),
  },
  {
    id: "algonquin-park", slug: "algonquin-park", name: "Algonquin Provincial Park lakes",
    region: "Central Ontario", municipality: "Nipissing / Haliburton districts", bodyType: "lake-shore", fmz: "fmz-15",
    fmzNote: "The park contains many waters and special rules; verify the exact lake.",
    coordinates: { latitude: 45.58, longitude: -78.36 },
    accessModes: ["shore", "kayak", "boat", "fly", "ice"], shoreSuitability: "limited", familyFriendly: false,
    popularity: "featured", parking: "Permit parking is available at designated access points.",
    fees: "Provincial park day-use, camping, and reservation fees apply.",
    facilities: ["access-point offices", "campgrounds", "canoe rentals", "backcountry campsites"],
    directionsUrl: directions("Algonquin Provincial Park Ontario"), fishOnlineUrl,
    expectedSpecies: ["Brook trout", "Lake trout", "Smallmouth bass", "Northern pike"],
    beginnerTargets: ["smallmouth bass"],
    tackleNotes: "Light canoe-compatible tackle; troll small spoons for trout where open or cast compact bass lures.",
    accessNotes: "Choose a specific road-access lake or planned canoe route; many lakes require portaging.",
    baitRules: "Park-specific live baitfish restrictions and FMZ 15 rules apply.",
    cautions: ["Remote travel requires route planning, permits, weather awareness, PFDs, and self-rescue capability.", "Cold water and limited communications are serious risks."],
    sources: sources("Algonquin Provincial Park", true),
  },
  {
    id: "bay-of-quinte", slug: "bay-of-quinte", name: "Bay of Quinte",
    region: "Eastern Ontario", municipality: "Belleville / Quinte West / Prince Edward County", bodyType: "bay-harbour", fmz: "fmz-20",
    coordinates: { latitude: 44.16, longitude: -77.25 },
    accessModes: ["shore", "pier", "boat", "kayak", "ice"], shoreSuitability: "good", familyFriendly: true,
    popularity: "featured", parking: "Municipal waterfront and launch parking is available in several communities.",
    fees: "Some launches, marinas, parking areas, and charters charge.",
    facilities: ["boat launches", "marinas", "waterfront parks", "charters"],
    directionsUrl: directions("Bay of Quinte Belleville Ontario"), fishOnlineUrl,
    expectedSpecies: ["Walleye", "Largemouth bass", "Smallmouth bass", "Northern pike", "Yellow perch", "Freshwater drum"],
    beginnerTargets: ["yellow perch", "bass"],
    tackleNotes: "Small jigs from shore, or boat-based jigging and trolling for walleye; plastics and crankbaits for bass.",
    accessNotes: "Choose a named waterfront park or launch; broad sections are boat-oriented.",
    baitRules: "FMZ 20 rules and Bay of Quinte exceptions apply.",
    cautions: ["Wind, current, shipping traffic, and late-season cold water require big-water precautions.", "Verify ice locally before access."],
    sources: sources("Bay of Quinte", true),
  },
  {
    id: "st-lawrence-thousand-islands", slug: "st-lawrence-thousand-islands", name: "St. Lawrence River / Thousand Islands",
    region: "Eastern Ontario", municipality: "Kingston / Gananoque / Brockville", bodyType: "river", fmz: "fmz-20",
    coordinates: { latitude: 44.34, longitude: -76.05 },
    accessModes: ["pier", "boat", "kayak"], shoreSuitability: "limited", familyFriendly: false,
    popularity: "featured", parking: "Municipal harbour, launch, and waterfront parking varies by town.",
    fees: "Launch, marina, parking, and national-park fees may apply.",
    facilities: ["marinas", "boat launches", "charters", "waterfront parks"],
    directionsUrl: directions("Thousand Islands Ontario"), fishOnlineUrl,
    expectedSpecies: ["Smallmouth bass", "Muskellunge", "Northern pike", "Walleye", "Yellow perch"],
    beginnerTargets: ["smallmouth bass", "yellow perch"],
    tackleNotes: "Drop-shots and tubes for bass; trolling and specialized heavy tackle for experienced muskie anglers.",
    accessNotes: "Use a defined municipal access or outfitter; much of this fast, deep international water is boat-oriented.",
    baitRules: "FMZ 20 rules, exceptions, and international boundary requirements apply.",
    cautions: ["Strong current, deep cold water, shoals, and commercial traffic demand charts and full safety equipment.", "Do not cross the international border without understanding reporting rules."],
    sources: sources("Thousand Islands Ontario", true),
  },
  {
    id: "rideau-lakes", slug: "rideau-lakes", name: "Rideau Lakes and Canal",
    region: "Eastern Ontario", municipality: "Rideau Lakes / Smiths Falls", bodyType: "lake-shore", fmz: "fmz-18",
    coordinates: { latitude: 44.68, longitude: -76.22 },
    accessModes: ["shore", "pier", "boat", "kayak", "ice"], shoreSuitability: "good", familyFriendly: true,
    popularity: "popular", parking: "Municipal launches, parks, and some lockstations provide parking.",
    fees: "Launch, lockage, mooring, and some parking fees apply.",
    facilities: ["lockstations", "boat launches", "washrooms seasonally", "marinas"],
    directionsUrl: directions("Rideau Lakes Ontario"), fishOnlineUrl,
    expectedSpecies: ["Largemouth bass", "Smallmouth bass", "Northern pike", "Walleye", "Crappie", "Yellow perch"],
    beginnerTargets: ["bass", "crappie", "yellow perch"],
    tackleNotes: "Weedless plastics, spinnerbaits, small crankbaits, and panfish jigs suit many accessible areas.",
    accessNotes: "Choose a specific lake, lockstation, or municipal access and obey posted Parks Canada restrictions.",
    baitRules: "FMZ 18 rules and waterbody exceptions apply.",
    cautions: ["Keep clear of lock approaches and navigation lanes.", "Current near dams and lock structures can be dangerous."],
    sources: sources("Rideau Lakes Ontario", true),
  },
  {
    id: "ottawa-river", slug: "ottawa-river", name: "Ottawa River",
    region: "Eastern Ontario", municipality: "Ottawa / Renfrew / Pembroke", bodyType: "river", fmz: "fmz-12",
    fmzNote: "The Ontario–Quebec boundary water has FMZ 12 exceptions; verify the exact reach.",
    coordinates: { latitude: 45.43, longitude: -75.7 },
    accessModes: ["shore", "pier", "boat", "kayak", "ice"], shoreSuitability: "good", familyFriendly: true,
    popularity: "featured", parking: "Municipal waterfront and launch parking varies by reach.",
    fees: "Some launches, marinas, and parking areas charge.",
    facilities: ["waterfront parks", "boat launches", "marinas", "urban amenities"],
    directionsUrl: directions("Ottawa River Ottawa Ontario"), fishOnlineUrl,
    expectedSpecies: ["Walleye", "Muskellunge", "Smallmouth bass", "Largemouth bass", "Northern pike", "Channel catfish"],
    beginnerTargets: ["bass", "channel catfish"],
    tackleNotes: "Shore jigs and bottom rigs in accessible urban reaches; boat anglers use trolling, casting, and electronics.",
    accessNotes: "Access and conditions vary dramatically; select a named park or launch.",
    baitRules: "FMZ 12 boundary-water rules and reach-specific exceptions apply.",
    cautions: ["Current, dams, rapids, cold water, and interprovincial rules require exact-location planning.", "Never approach exclusion booms or generating stations."],
    sources: sources("Ottawa River Ontario", true),
  },
  {
    id: "lake-nipissing", slug: "lake-nipissing", name: "Lake Nipissing",
    region: "Northeastern Ontario", municipality: "North Bay / West Nipissing", bodyType: "large-lake", fmz: "fmz-11",
    coordinates: { latitude: 46.25, longitude: -79.8 },
    accessModes: ["pier", "boat", "kayak", "ice"], shoreSuitability: "limited", familyFriendly: false,
    popularity: "featured", parking: "Municipal and commercial launch parking around North Bay and West Nipissing.",
    fees: "Launch, marina, hut, charter, and parking fees may apply.",
    facilities: ["marinas", "boat launches", "ice-hut operators", "lodges"],
    directionsUrl: directions("Lake Nipissing Ontario"), fishOnlineUrl,
    expectedSpecies: ["Walleye", "Northern pike", "Muskellunge", "Smallmouth bass", "Yellow perch"],
    beginnerTargets: ["yellow perch", "smallmouth bass"],
    tackleNotes: "Jig or troll for walleye, cast weed edges for pike and bass, and use small jigs for perch.",
    accessNotes: "This broad, shallow lake is primarily boat- or outfitter-oriented; choose a protected access.",
    baitRules: "FMZ 11 rules and Lake Nipissing-specific exceptions apply.",
    cautions: ["Wind creates steep waves quickly and shallow rock hazards are widespread.", "Use a reputable operator for winter travel and never assume ice safety."],
    sources: sources("Lake Nipissing", true),
  },
  {
    id: "french-river", slug: "french-river", name: "French River",
    region: "Northeastern Ontario", municipality: "French River / Killarney", bodyType: "river", fmz: "fmz-10",
    fmzNote: "The river system crosses regulatory and park contexts; verify the exact reach.",
    coordinates: { latitude: 46.02, longitude: -80.62 },
    accessModes: ["boat", "kayak"], shoreSuitability: "boat-oriented", familyFriendly: false,
    popularity: "featured", parking: "Access is commonly through lodges, outfitters, or designated park access points.",
    fees: "Park, launch, camping, outfitter, and lodge fees may apply.",
    facilities: ["lodges", "outfitters", "backcountry campsites", "boat launches"],
    directionsUrl: directions("French River Provincial Park Ontario"), fishOnlineUrl,
    expectedSpecies: ["Walleye", "Muskellunge", "Northern pike", "Smallmouth bass", "Lake sturgeon"],
    beginnerTargets: ["smallmouth bass", "northern pike"],
    tackleNotes: "Boat or canoe casting and jigging; carry release tools and tackle matched to large pike or muskie.",
    accessNotes: "A remote waterway with rapids, portages, and large open reaches; plan with a park access point or outfitter.",
    baitRules: "Verify FMZ, bait management zone, park rules, and species exceptions for the exact reach.",
    cautions: ["Rapids, cold water, remoteness, limited communications, and Georgian Bay weather require advanced trip planning.", "Lake sturgeon are highly regulated—verify rules and release immediately where required."],
    sources: sources("French River Ontario", true),
  },
  {
    id: "lake-temagami", slug: "lake-temagami", name: "Lake Temagami",
    region: "Northeastern Ontario", municipality: "Temagami", bodyType: "large-lake", fmz: "fmz-11",
    coordinates: { latitude: 46.98, longitude: -80.08 },
    accessModes: ["boat", "kayak", "ice"], shoreSuitability: "boat-oriented", familyFriendly: false,
    popularity: "featured", parking: "Use designated landings, marinas, lodges, or outfitters; secure vehicle and trailer arrangements.",
    fees: "Launch, parking, water taxi, lodge, and outfitter fees vary.",
    facilities: ["marinas", "lodges", "outfitters", "backcountry campsites"],
    directionsUrl: directions("Lake Temagami Ontario"), fishOnlineUrl,
    expectedSpecies: ["Lake trout", "Walleye", "Smallmouth bass", "Northern pike", "Whitefish"],
    beginnerTargets: ["smallmouth bass"],
    tackleNotes: "Troll or jig for deep-water fish and cast rocky shorelines for bass; navigation electronics are strongly recommended.",
    accessNotes: "A vast island-filled lake requiring an exact landing, route, and destination.",
    baitRules: "FMZ 11 and waterbody-specific rules apply; verify bait movement requirements.",
    cautions: ["Remote open water, cold temperatures, reefs, and complex navigation make this boat-oriented.", "File a trip plan and carry redundant navigation and communication."],
    sources: sources("Lake Temagami", true),
  },
  {
    id: "lady-evelyn-smoothwater", slug: "lady-evelyn-smoothwater", name: "Lady Evelyn-Smoothwater backcountry lakes",
    region: "Northeastern Ontario", municipality: "Timiskaming District", bodyType: "lake-shore", fmz: "fmz-11",
    coordinates: { latitude: 47.32, longitude: -80.48 },
    accessModes: ["kayak", "fly"], shoreSuitability: "boat-oriented", familyFriendly: false,
    popularity: "local", parking: "Remote access-point parking requires route-specific planning and may involve an outfitter.",
    fees: "Backcountry permits, shuttles, and outfitter fees may apply.",
    facilities: ["backcountry campsites", "portages", "outfitter access"],
    directionsUrl: directions("Lady Evelyn Smoothwater Provincial Park Ontario"), fishOnlineUrl,
    expectedSpecies: ["Brook trout", "Lake trout", "Walleye", "Northern pike"],
    beginnerTargets: ["none; experienced backcountry anglers"],
    tackleNotes: "Pack compact canoe and fly tackle, barbless release tools where required, and minimal species-appropriate lures.",
    accessNotes: "Remote canoe-route destination, not a roadside fishing site.",
    baitRules: "Park, FMZ 11, and exact-lake bait restrictions must be checked before packing bait.",
    cautions: ["Advanced wilderness travel only: portages, rapids, cold water, bears, and no reliable communications.", "Carry emergency communication and leave a detailed trip plan."],
    sources: sources("Lady Evelyn Smoothwater Provincial Park", true),
  },
  {
    id: "lake-superior", slug: "lake-superior", name: "Lake Superior",
    region: "Northwestern Ontario", municipality: "Thunder Bay / Wawa / Marathon", bodyType: "large-lake", fmz: "fmz-9",
    fmzNote: "Tributaries and inland waters use different zones; verify the exact location.",
    coordinates: { latitude: 48.55, longitude: -87.45 },
    accessModes: ["pier", "boat", "kayak"], shoreSuitability: "limited", familyFriendly: false,
    popularity: "featured", parking: "Harbour, marina, provincial-park, and launch parking varies by community.",
    fees: "Park, marina, launch, charter, and parking fees may apply.",
    facilities: ["marinas", "boat launches", "charters", "provincial parks"],
    directionsUrl: directions("Lake Superior Ontario"), fishOnlineUrl,
    expectedSpecies: ["Lake trout", "Chinook salmon", "Coho salmon", "Steelhead", "Brook trout", "Whitefish"],
    beginnerTargets: ["seasonal fish from a managed pier or charter"],
    tackleNotes: "Shore spoons at suitable accesses; open-water salmon and trout usually require a properly equipped boat or charter.",
    accessNotes: "Select a protected harbour, established shore site, or licensed charter; the regional pin is not an access point.",
    baitRules: "FMZ 9 rules, Great Lakes bait rules, and tributary exceptions apply.",
    cautions: ["Extremely cold water, fog, sudden storms, surf, and long distances make this serious big water.", "Open-water kayaking requires sea-kayak expertise, immersion gear, and conservative forecasts."],
    sources: sources("Lake Superior Ontario", true),
  },
  {
    id: "lake-of-the-woods", slug: "lake-of-the-woods", name: "Lake of the Woods",
    region: "Northwestern Ontario", municipality: "Kenora / Sioux Narrows-Nestor Falls", bodyType: "large-lake", fmz: "fmz-5",
    coordinates: { latitude: 49.25, longitude: -94.5 },
    accessModes: ["boat", "kayak", "ice"], shoreSuitability: "boat-oriented", familyFriendly: false,
    popularity: "featured", parking: "Public and commercial launch parking is available near Kenora and resort communities.",
    fees: "Launch, marina, lodge, guide, and ice-service fees vary.",
    facilities: ["marinas", "lodges", "guides", "boat launches", "ice services"],
    directionsUrl: directions("Lake of the Woods Kenora Ontario"), fishOnlineUrl,
    expectedSpecies: ["Walleye", "Muskellunge", "Northern pike", "Smallmouth bass", "Lake trout", "Crappie"],
    beginnerTargets: ["walleye with a guide", "smallmouth bass"],
    tackleNotes: "Jig and troll for walleye, cast rock for bass, and use specialized heavy gear and release tools for muskie.",
    accessNotes: "A vast international lake with thousands of islands; use a resort, guide, or precise launch and route.",
    baitRules: "FMZ 5 and Lake of the Woods exceptions apply; border-water rules may also matter.",
    cautions: ["Complex navigation, reefs, cold water, storms, wildfire impacts, and border issues demand careful planning.", "Winter travel should be through maintained local routes or operators."],
    sources: sources("Lake of the Woods Ontario", true),
  },
  {
    id: "rainy-lake", slug: "rainy-lake", name: "Rainy Lake",
    region: "Northwestern Ontario", municipality: "Fort Frances", bodyType: "large-lake", fmz: "fmz-5",
    coordinates: { latitude: 48.63, longitude: -93.1 },
    accessModes: ["boat", "kayak", "ice"], shoreSuitability: "boat-oriented", familyFriendly: false,
    popularity: "featured", parking: "Municipal, resort, and commercial launch parking around Fort Frances and nearby communities.",
    fees: "Launch, lodge, guide, parking, and ice-service fees may apply.",
    facilities: ["boat launches", "lodges", "guides", "marinas"],
    directionsUrl: directions("Rainy Lake Fort Frances Ontario"), fishOnlineUrl,
    expectedSpecies: ["Walleye", "Smallmouth bass", "Northern pike", "Crappie", "Lake trout"],
    beginnerTargets: ["walleye with a guide", "smallmouth bass"],
    tackleNotes: "Jig or troll reefs for walleye and cast tubes or topwaters for bass; electronics improve safe navigation.",
    accessNotes: "Large international border water best approached through a local launch, lodge, or guide.",
    baitRules: "FMZ 5, waterbody exceptions, and border-water requirements apply.",
    cautions: ["Wind, reefs, cold water, long runs, wildfire smoke, and border crossings require conservative decisions.", "Use verified local ice roads or operators in winter."],
    sources: sources("Rainy Lake Ontario", true),
  },
  {
    id: "eagle-lake", slug: "eagle-lake", name: "Eagle Lake",
    region: "Northwestern Ontario", municipality: "Machin / Eagle Lake", bodyType: "large-lake", fmz: "fmz-5",
    coordinates: { latitude: 49.7, longitude: -93.2 },
    accessModes: ["boat", "kayak", "ice"], shoreSuitability: "boat-oriented", familyFriendly: false,
    popularity: "popular", parking: "Access is mainly through lodges, resorts, and designated launches.",
    fees: "Launch, lodge, guide, and rental fees vary.",
    facilities: ["lodges", "guides", "boat launches", "rentals"],
    directionsUrl: directions("Eagle Lake Ontario fishing"), fishOnlineUrl,
    expectedSpecies: ["Muskellunge", "Walleye", "Northern pike", "Smallmouth bass", "Lake trout"],
    beginnerTargets: ["walleye with a guide", "smallmouth bass"],
    tackleNotes: "Jig or troll for walleye, cast rock for bass, and use heavy tackle plus release tools for muskie.",
    accessNotes: "A large, structure-rich lake where a lodge or guide simplifies access and navigation.",
    baitRules: "FMZ 5 rules and waterbody exceptions apply.",
    cautions: ["Remote reefs, weather, cold water, and limited cell service make this boat-oriented.", "Muskie fishing requires safe handling equipment and experience."],
    sources: sources("Eagle Lake Ontario", true),
  },
  {
    id: "lac-seul", slug: "lac-seul", name: "Lac Seul",
    region: "Northwestern Ontario", municipality: "Sioux Lookout / Ear Falls", bodyType: "reservoir", fmz: "fmz-4",
    coordinates: { latitude: 50.25, longitude: -92.25 },
    accessModes: ["boat", "ice"], shoreSuitability: "boat-oriented", familyFriendly: false,
    popularity: "featured", parking: "Use lodge, outfitter, or designated launch parking arranged in advance.",
    fees: "Launch, lodge, guide, fly-in, and ice-service fees can be substantial.",
    facilities: ["lodges", "guides", "boat launches", "remote outposts"],
    directionsUrl: directions("Lac Seul Ontario"), fishOnlineUrl,
    expectedSpecies: ["Walleye", "Northern pike", "Muskellunge", "Smallmouth bass", "Yellow perch"],
    beginnerTargets: ["walleye with a guide"],
    tackleNotes: "Jig, troll, or cast from a properly equipped boat; local knowledge is valuable around reservoir structure.",
    accessNotes: "A very large remote reservoir best accessed with a lodge, outfitter, or experienced local guide.",
    baitRules: "FMZ 4 and Lac Seul-specific exceptions apply; verify bait management restrictions.",
    cautions: ["Remote navigation, submerged timber and rock, sudden weather, wildfire impacts, and poor communications are major hazards.", "Use local operators for winter travel."],
    sources: sources("Lac Seul Ontario", true),
  },
  {
    id: "nipigon-river", slug: "nipigon-river", name: "Nipigon River and Lake Nipigon",
    region: "Northwestern Ontario", municipality: "Nipigon / Red Rock", bodyType: "river", fmz: "fmz-6",
    fmzNote: "Lake Nipigon and the river have significant species-specific exceptions.",
    coordinates: { latitude: 49.02, longitude: -88.26 },
    accessModes: ["boat", "fly"], shoreSuitability: "boat-oriented", familyFriendly: false,
    popularity: "featured", parking: "Arrange access through named launches, outfitters, or local parks; remote sites vary.",
    fees: "Launch, guide, outfitter, and park fees may apply.",
    facilities: ["guides", "boat launches", "campgrounds", "lodges"],
    directionsUrl: directions("Nipigon River Ontario"), fishOnlineUrl,
    expectedSpecies: ["Brook trout", "Lake trout", "Chinook salmon", "Coho salmon", "Walleye", "Northern pike"],
    beginnerTargets: ["none; guided trip recommended"],
    tackleNotes: "Specialized fly, casting, or trolling gear matched to current regulations and powerful fish.",
    accessNotes: "Use an experienced local guide for river reaches, current, and Lake Nipigon's exposed water.",
    baitRules: "FMZ 6 special regulations and exact-waterbody bait restrictions must be reviewed.",
    cautions: ["Powerful current, dams, cold water, remoteness, and rapidly changing weather make this an advanced destination.", "Handle trophy brook trout carefully and obey all size and possession rules."],
    sources: sources("Nipigon River Ontario", true),
  },
  {
    id: "quetico-park", slug: "quetico-park", name: "Quetico Provincial Park lakes",
    region: "Northwestern Ontario", municipality: "Rainy River District", bodyType: "lake-shore", fmz: "fmz-5",
    coordinates: { latitude: 48.45, longitude: -91.5 },
    accessModes: ["kayak", "fly"], shoreSuitability: "boat-oriented", familyFriendly: false,
    popularity: "featured", parking: "Permit parking is available at designated access points; some routes require outfitter transport.",
    fees: "Backcountry permits, reservations, rentals, and outfitter services apply.",
    facilities: ["backcountry campsites", "portages", "ranger stations", "outfitters"],
    directionsUrl: directions("Quetico Provincial Park Ontario"), fishOnlineUrl,
    expectedSpecies: ["Smallmouth bass", "Walleye", "Northern pike", "Lake trout"],
    beginnerTargets: ["none; experienced canoe trippers"],
    tackleNotes: "Pack compact canoe tackle, lead-free alternatives where required, and dependable release tools.",
    accessNotes: "Remote wilderness canoe routes with portages; select an entry point and complete permit planning.",
    baitRules: "Quetico prohibits live baitfish and has tackle restrictions; confirm current park and FMZ 5 rules.",
    cautions: ["Advanced wilderness travel with cold water, portages, storms, wildfire risk, bears, and no dependable cell service.", "Carry emergency communication, maps, PFDs, and a detailed trip plan."],
    sources: sources("Quetico Provincial Park", true),
  },
  {
    id: "grand-river", slug: "grand-river", name: "Grand River",
    region: "Southern Ontario", municipality: "Fergus / Elora / Brantford", bodyType: "river", fmz: "fmz-16",
    fmzNote: "The Grand is many fisheries in one; verify the exact reach and fly-fishing or sanctuary rules.",
    coordinates: { latitude: 43.7, longitude: -80.43 },
    accessModes: ["shore", "fly", "kayak"], shoreSuitability: "good", familyFriendly: false,
    popularity: "featured", parking: "Municipal and conservation-area parking varies by reach.",
    fees: "Some conservation areas, parks, and private accesses charge.",
    facilities: ["conservation areas", "trails", "fly shops nearby"],
    directionsUrl: directions("Grand River Elora Ontario fishing"), fishOnlineUrl,
    expectedSpecies: ["Brown trout", "Rainbow trout", "Smallmouth bass", "Walleye", "Northern pike", "Channel catfish"],
    beginnerTargets: ["smallmouth bass", "brown trout where open"],
    tackleNotes: "Upper river: flies and light spoons. Middle and lower: smallmouth plastics, walleye jigs, and catfish bottom rigs where legal.",
    accessNotes: "Choose a named conservation area or municipal park rather than treating the whole river as one spot.",
    baitRules: "FMZ 16 Southern Bait Management Zone rules apply; some reaches are fly or artificial only.",
    cautions: ["Current, dams, and slippery rocks are serious hazards.", "Confirm private-land boundaries and posted sanctuary dates."],
    sources: sources("Grand River Ontario", true),
  },
  {
    id: "credit-river", slug: "credit-river", name: "Credit River",
    region: "Southern Ontario", municipality: "Mississauga / Streetsville / Erindale", bodyType: "river-tributary", fmz: "fmz-16",
    fmzNote: "Lake Ontario tributary with section-specific exceptions and sanctuary dates.",
    coordinates: { latitude: 43.58, longitude: -79.65 },
    accessModes: ["shore", "fly"], shoreSuitability: "good", familyFriendly: false, popularity: "popular",
    parking: "Municipal park parking along the lower Credit; spaces fill during the salmon run.",
    fees: "Most municipal parks are free; conservation areas may charge.",
    facilities: ["trails", "washrooms in some parks", "transit nearby"],
    directionsUrl: directions("Credit River Mississauga fishing"), fishOnlineUrl,
    expectedSpecies: ["Chinook salmon", "Coho salmon", "Rainbow trout", "Brown trout", "Atlantic salmon"],
    beginnerTargets: ["seasonal salmon/trout"],
    tackleNotes: "Spoons, spinners, beads, or flies only where that method is legal on that section.",
    accessNotes: "Fish only from public park access. Tributary rules change by section and date.",
    baitRules: "FMZ 16 tributary bait, hook, and sanctuary rules apply.",
    cautions: ["Do not wade high or fast water.", "Crowding during runs requires extra courtesy and exact-rule checks."],
    sources: sources("Credit River Ontario"),
  },
  {
    id: "hamilton-harbour", slug: "hamilton-harbour", name: "Hamilton Harbour / Bayfront",
    region: "Southern Ontario", municipality: "Hamilton", bodyType: "bay-harbour", fmz: "fmz-16",
    fmzNote: "Harbour, canal, and Lake Ontario waters meet nearby; verify the exact fishing position.",
    coordinates: { latitude: 43.27, longitude: -79.87 },
    accessModes: ["shore", "pier", "kayak"], shoreSuitability: "good", familyFriendly: true, popularity: "popular",
    parking: "Bayfront and harbour-area municipal lots.",
    fees: "Some parking lots charge; park access is generally free.",
    facilities: ["trails", "washrooms seasonally", "piers", "transit nearby"],
    directionsUrl: directions("Bayfront Park Hamilton Ontario fishing"), fishOnlineUrl,
    expectedSpecies: ["Northern pike", "Largemouth bass", "Yellow perch", "Carp", "Brown bullhead", "Seasonal salmon/trout"],
    beginnerTargets: ["pike", "bass", "perch", "carp"],
    tackleNotes: "Weedless bass plastics, pike spoons with a leader, small perch jigs, and carp bottom rigs where bait is allowed.",
    accessNotes: "Urban harbour parks and piers; stay off industrial and posted shorelines.",
    baitRules: "Confirm whether you are in FMZ 16 harbour water or nearby Lake Ontario (FMZ 20).",
    cautions: ["Shipping, current at the canal, and industrial shorelines are off-limits.", "Water quality advisories can apply; check eating-fish guidance."],
    sources: sources("Hamilton Harbour Ontario"),
  },
  {
    id: "niagara-river", slug: "niagara-river", name: "Niagara River",
    region: "Southern Ontario", municipality: "Niagara-on-the-Lake / Fort Erie", bodyType: "river", fmz: "fmz-20",
    fmzNote: "Powerful international boundary water with reach-specific exceptions.",
    coordinates: { latitude: 43.08, longitude: -79.07 },
    accessModes: ["shore", "pier", "boat"], shoreSuitability: "limited", familyFriendly: false, popularity: "featured",
    parking: "Municipal and parkway lots; some fill quickly during runs.",
    fees: "Parks, launches, and some lots charge.",
    facilities: ["parks", "piers", "charters", "boat launches"],
    directionsUrl: directions("Niagara River fishing Ontario"), fishOnlineUrl,
    expectedSpecies: ["Rainbow trout", "Brown trout", "Chinook salmon", "Smallmouth bass", "Walleye", "Muskellunge"],
    beginnerTargets: ["seasonal trout/salmon from legal public access"],
    tackleNotes: "Heavy spoons and bottom rigs in current; this is not a light-tackle beginner river.",
    accessNotes: "Use named public parks only. Current and shipping make much of the river advanced.",
    baitRules: "FMZ 20, tributary, and international boundary rules can all apply.",
    cautions: ["Extremely strong current, sudden drops, and shipping traffic.", "Never approach generating stations or exclusion zones."],
    sources: sources("Niagara River Ontario", true),
  },
  {
    id: "port-dover", slug: "port-dover", name: "Port Dover / Lake Erie shore",
    region: "Southern Ontario", municipality: "Norfolk County", bodyType: "lake-shore", fmz: "fmz-19",
    coordinates: { latitude: 42.785, longitude: -80.2 },
    accessModes: ["pier", "shore", "boat"], shoreSuitability: "good", familyFriendly: true, popularity: "popular",
    parking: "Harbour and beach-area parking; busy in summer.",
    fees: "Some lots and launches charge.",
    facilities: ["piers", "harbour", "washrooms seasonally", "charters"],
    directionsUrl: directions("Port Dover Ontario fishing pier"), fishOnlineUrl,
    expectedSpecies: ["Yellow perch", "Walleye", "Smallmouth bass", "Rainbow trout", "Pacific salmon"],
    beginnerTargets: ["yellow perch"],
    tackleNotes: "Small jigs and worm pieces for perch from piers; walleye is usually a boat fishery.",
    accessNotes: "Piers and harbour walls are the practical shore options; open lake is boat-oriented.",
    baitRules: "FMZ 19 Lake Erie rules and harbour exceptions apply.",
    cautions: ["Lake Erie waves and seiches change quickly.", "Stay off spray-covered piers in wind."],
    sources: sources("Port Dover Ontario", true),
  },
  {
    id: "lake-st-clair", slug: "lake-st-clair", name: "Lake St. Clair",
    region: "Southern Ontario", municipality: "Windsor / Tecumseh / Lakeshore", bodyType: "large-lake", fmz: "fmz-19",
    fmzNote: "Shallow connecting water with the Detroit and St. Clair rivers. Confirm the exact Ontario reach; Michigan water is adjacent.",
    coordinates: { latitude: 42.4, longitude: -82.4 },
    accessModes: ["pier", "boat", "kayak", "ice"], shoreSuitability: "limited", familyFriendly: true, popularity: "featured",
    parking: "Municipal launches and waterfront parks; trailer parking varies.",
    fees: "Launch, parking, and marina fees are common.",
    facilities: ["boat launches", "marinas", "waterfront parks"],
    directionsUrl: directions("Lake St Clair Ontario fishing"), fishOnlineUrl,
    expectedSpecies: ["Walleye", "Largemouth bass", "Smallmouth bass", "Muskellunge", "Yellow perch"],
    beginnerTargets: ["yellow perch", "bass from accessible parks"],
    tackleNotes: "Perch jigs from piers; bass plastics in remaining weeds; walleye and muskie are mostly boat fisheries.",
    accessNotes: "Choose a named Ontario launch or park. Much of the productive water is boat-oriented.",
    baitRules: "FMZ 13 rules and Great Lakes bait-management plus boundary-water requirements apply.",
    cautions: ["Shallow water becomes dangerous in wind.", "Do not cross into US water without understanding reporting rules."],
    sources: sources("Lake St. Clair Ontario", true),
  },
];

export const fishingLocations: FishingLocation[] = rawLocations.map(enrichLocation);

export function getLocationById(id: string): FishingLocation | undefined {
  return fishingLocations.find((location) => location.id === id || location.slug === id);
}
